//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class AdminPanel {
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.GridView ProductGrid;

		protected System.Web.UI.WebControls.GridView UserGrid;

		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.TextBox id;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox price;
		
		protected System.Web.UI.WebControls.TextBox category;
		
		protected System.Web.UI.WebControls.TextBox description;
		
		protected System.Web.UI.WebControls.TextBox image;
	}
}
