//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class CartItem {
		
		protected System.Web.UI.WebControls.Content body;
		protected global::System.Web.UI.WebControls.Button buttonInCart;
		protected global::System.Web.UI.WebControls.Label item1;
		protected global::System.Web.UI.WebControls.Label item2;
		protected global::System.Web.UI.WebControls.Label item3;
		protected global::System.Web.UI.WebControls.Label item4;
		protected global::System.Web.UI.WebControls.Label item5;
		protected global::System.Web.UI.WebControls.Label item6;

	}
}
