//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class Home {
		
		protected System.Web.UI.WebControls.Content body;
		protected global::System.Web.UI.WebControls.TextBox StartDate1;
		protected global::System.Web.UI.WebControls.TextBox StartDate2;
		protected global::System.Web.UI.WebControls.TextBox EndDate1;
		protected global::System.Web.UI.WebControls.TextBox EndDate2;

	}
}
