//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {


	public partial class Master {

		protected System.Web.UI.HtmlControls.HtmlGenericControl LoginOutButton;

		protected System.Web.UI.HtmlControls.HtmlButton HomeButton;

		protected System.Web.UI.HtmlControls.HtmlButton ProductsButton;

		protected System.Web.UI.HtmlControls.HtmlButton ContactButton;

		protected System.Web.UI.HtmlControls.HtmlButton AboutButton;

		protected System.Web.UI.WebControls.ContentPlaceHolder bodyContent;

		public global::System.Web.UI.WebControls.Button ShoppingCart;

		protected global::System.Web.UI.WebControls.Label cartLabel;

		protected global::System.Web.UI.HtmlControls.HtmlGenericControl nav;
	}
}
