//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class OrderHistory {
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.Label deletedId;
		
		protected System.Web.UI.WebControls.GridView orderHistory;
		
		protected System.Web.UI.WebControls.Label Label4h;
		
		protected System.Web.UI.WebControls.Image Imageh;
		
		protected System.Web.UI.WebControls.Label Label1h;
		
		protected System.Web.UI.WebControls.Label Label2h;
		
		protected System.Web.UI.WebControls.Label Label3h;
		
		protected System.Web.UI.WebControls.Label Label5h;
	}
}
