//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class Products {
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.DataList PRODUCTS;
		
		protected System.Web.UI.WebControls.Button addToCartButton;
	}
}
