//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental
{


	public partial class Products
	{

		protected System.Web.UI.WebControls.Content body;
		protected global::System.Web.UI.WebControls.TextBox daysRented1;
		protected global::System.Web.UI.WebControls.TextBox daysRented2;
		protected global::System.Web.UI.WebControls.TextBox daysRented3;
		protected global::System.Web.UI.WebControls.TextBox daysRented4;
		protected global::System.Web.UI.WebControls.TextBox daysRented5;
		protected global::System.Web.UI.WebControls.TextBox daysRented6;
	}
}
