//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental
{


	public partial class Products
	{

		protected System.Web.UI.WebControls.Content body;
		protected global::System.Web.UI.WebControls.TextBox StartDate1;
		protected global::System.Web.UI.WebControls.TextBox StartDate2;
		protected global::System.Web.UI.WebControls.TextBox StartDate3;
		protected global::System.Web.UI.WebControls.TextBox StartDate4;
		protected global::System.Web.UI.WebControls.TextBox StartDate5;
		protected global::System.Web.UI.WebControls.TextBox StartDate6;
		protected global::System.Web.UI.WebControls.TextBox EndDate1;
		protected global::System.Web.UI.WebControls.TextBox EndDate2;
		protected global::System.Web.UI.WebControls.TextBox EndDate3;
		protected global::System.Web.UI.WebControls.TextBox EndDate4;
		protected global::System.Web.UI.WebControls.TextBox EndDate5;
		protected global::System.Web.UI.WebControls.TextBox EndDate6;
	}
}
