//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigCarRental {
	
	
	public partial class SignUp {
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.Label loginLabel;
		
		protected System.Web.UI.WebControls.TextBox firstName;
		
		protected System.Web.UI.WebControls.TextBox lastName;
		
		protected System.Web.UI.WebControls.TextBox Username;
		
		protected System.Web.UI.WebControls.TextBox Pasword;
		
		protected System.Web.UI.WebControls.TextBox confirmPasword;
		
		protected System.Web.UI.WebControls.Button SIGNUP;
	}
}
